# Generated by Django 4.1.3 on 2022-11-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
