# Generated by Django 4.1.3 on 2022-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0002_remove_category_slug_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.CharField(max_length=200)),
            ],
        ),
    ]
