# Generated by Django 4.1.3 on 2022-11-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0003_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
