# Generated by Django 4.1.3 on 2022-11-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0004_remove_author_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Read More', max_length=200),
        ),
    ]
