# Generated by Django 4.1.2 on 2022-11-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0005_remove_post_categories_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='homepage',
            new_name='project_title',
        ),
    ]
