# Generated by Django 4.1.2 on 2022-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0006_rename_homepage_home_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='check_code',
            field=models.URLField(default=' ', max_length=300, verbose_name='Check_code'),
        ),
        migrations.AddField(
            model_name='home',
            name='live_page',
            field=models.URLField(default=' ', max_length=300, verbose_name='Live_page'),
        ),
    ]
