# Generated by Django 4.1.2 on 2022-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0007_home_check_code_home_live_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='check_code',
            field=models.URLField(max_length=300, verbose_name='Check_code'),
        ),
        migrations.AlterField(
            model_name='home',
            name='live_page',
            field=models.URLField(max_length=300, verbose_name='Live_page'),
        ),
    ]
