# Generated by Django 4.1.2 on 2022-11-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0008_alter_home_check_code_alter_home_live_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
