# Generated by Django 4.1.2 on 2022-11-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0009_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Project',
        ),
    ]
