# Generated by Django 4.1.2 on 2022-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0010_rename_home_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='message',
            field=models.TextField(default=' '),
        ),
    ]
