# Generated by Django 4.1.2 on 2022-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0011_project_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='message',
            field=models.TextField(),
        ),
    ]
