# Generated by Django 4.1.2 on 2022-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogP', '0012_alter_project_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='check_code',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_page',
            field=models.URLField(max_length=300),
        ),
    ]
